// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type CartItem struct {
	ID         int64
	UserID     int64
	MenuItemID int64
	Quantity   int64
}

type Category struct {
	ID    int64
	Title string
}

type MenuItem struct {
	ID          int64
	Name        string
	Description sql.NullString
	ImageUrl    string
	Price       float64
	CategoryID  sql.NullInt64
}

type Order struct {
	ID         int64
	UserID     int64
	TotalPrice float64
	Status     string
	CreatedAt  sql.NullTime
}

type OrderItem struct {
	ID         int64
	OrderID    int64
	MenuItemID int64
	Quantity   int64
}

type Session struct {
	ID        int64
	UserID    int64
	Token     string
	ExpiresAt time.Time
	CreatedAt sql.NullTime
}

type User struct {
	ID       int64
	Username string
	Password string
	Email    string
	IsAdmin  int64
}
